### ISSUE TITLE
Boilerplate revision

### ISSUE THREAD

**Issue by ruymon** [Maua-Dev/clean_front_next_template#1]
Review the current stack and update it to the newest tendencies.

### ToDo:
- [ ] Bump to Next.js 15
- [ ] Migrate from Axios to native fetch to use Next.js caching features [Fetch | Next.js Docs](https://nextjs.org/docs/app/api-reference/functions/fetch)
- [ ] Inforce naming conventions
- [ ] Add ShadCN
- [ ] Add TailwindCSS
- [ ] Remove Babel (performance issues)
- [ ] Imrpove Docs
- [ ] Add SSR and Loading.tsx
